image: aharonamir/nebula3_experts_places:fcbd846
port: 8000
env:
  - name: ARANGO_DB
    value: prodemo
  - name: ARANGO_HOST
    value: 172.83.9.249
  - name: AWS_ACCESS_KEY_ID
    value: "${AWS_ACCESS_KEY_ID}"
  - name: AWS_SECRET_ACCESS_KEY
    value: "${AWS_SECRET_ACCESS_KEY}"

resources:
  replicas: 1
  instanceType: RTX4000
